### ISSUE TITLE
Solidworks で STL ファイルを出力するとき

### ISSUE THREAD

**Issue by TakakiNishio** [Nishida-Lab/motoman_cad#9]
STL ファイルを保存する際に出てくる画面で、「モデルの座標系で出力」にチェックを入れていないとその下の「出力座標系」を変更しても反映されません。当然といえば当然ですが私はハマりました。
※ Solidworks に限った話です。

![saving_stl](https://user-images.githubusercontent.com/18414264/30068309-56d8b19c-9298-11e7-8187-2a21617ce4c7.png)

**Comment by RyodoTanaka** [comment]
@TakakiNishio 
貴重な情報をありがとうございます！！！！！
